#!/bin/sh

# script with infinite loops to provide current data for status bar

xsetroot -name ""

while true; do
	date "+%F %R" > /tmp/CurTime.tmp
	ip addr | grep "inet 192" | cut -b 10-21 > /tmp/CurIP.tmp
	sleep 60s
done &


while true; do
	LOCALTIME=$(cat /tmp/CurTime.tmp)
	FREEMEM=$(free -h | grep "Mem:" | cut -b 40-43)
	BATTERY_LEVEL=$(acpi | grep -P -o '[0-9]+(?=%)')
	IP=$(cat /tmp/CurIP.tmp)
	VOL=$(amixer get Master | tail -n1 | sed -r 's/.*\[(.*)%\].*/\1/')
# here the bar line is generated:
	xsetroot -name "|wls1:$IP📡|$FREEMEM free💿|$VOL%🔊|$BATTERY_LEVEL%⛽|$LOCALTIME"
	sleep 10s


done &


